export const GET_FILTERS = "GET_FILTERS";
export const SET_INITIAL_FILTERS = "SET_INITIAL_FILTERS";
export const SET_FILTERS = "SET_FILTERS";
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GENERIC_ERROR = "GENERIC_ERROR"
export const GSM_FILTER = "GSM_FILTER"
export const UPDATE_SLIDER = "UPDATE_SLIDER"
export const CHANGE_SLIDER = "CHANGE_SLIDER"
export const TOGGLE_FILTER_SEARCH = "TOGGLE_FILTER_SEARCH"
export const QUERY_STRING = "QUERY_STRING"
export const GET_GROUPS = "GET_GROUPS"
export const EMPTY_PRODUCTS_ON_LOAD = "EMPTY_PRODUCTS_ON_LOAD"
export const GET_FILTERED_PRODUCTS_SHOP = "GET_FILTERED_PRODUCTS_SHOP"
export const TOGGLE_SHOP_TYPE = "TOGGLE_SHOP_TYPE"
export const SIZE_CHANGE = "SIZE_CHANGE";
export const GET_SEARCH_PRODUCTS = "GET_SEARCH_PRODUCTS";

