module.exports = function (app) {
  app
    .use("/customer", require("./users/customer"))
    .use("/supplier", require("./users/supplier"))
    .use("/auth", require("./auth"))
    .use("/menu", require("./menu"))
    .use("/master", require("./product/propertyMaster"))
    .use("/roles", require("./users/roles"))
    .use("/region", require("./region/region"))
    .use("/profile", require("./users/profile"))
    .use("/products", require("./product/productMaster"))
    .use("/targetYear", require("./Target/targetYear"))
    .use("/notifications", require("./notification"))
    .use("/pricing", require("./product/pricing"))
    .use("/customerGroups", require("./CustomerGroups"))
    .use("/warehouse", require("./warehouse"))
    .use("/inquiry", require("./Inquiry/customer"))
    .use("/supplierInquiry", require("./Inquiry/supplier"))
    .use("/dashboard", require("./Dashboard/index"))
    .use("/cart", require("./Cart/index"))
    .use("/order", require("./Order/index"))
    .use("/quotation", require("./Quotation/index"))
    .use("/address", require("./Address/index"))
    .use("/dispatch", require("./DispatchOrder/DispatchOrder"))
    .use("/customerHeader", require("./customerHeader"))
    .use("/terms", require("./TermsMaster"))
    .use("/chat", require("./Chat/Chat"))
};
