export const GET_COUNTRIES = "GET_COUNTRIES"
export const GET_COUNTRIES_ERROR = "GET_COUNTRIES_ERROR"
export const GET_STATES = "GET_STATES"
export const GET_STATES_ERROR = "GET_STATES_ERROR"
export const GET_CITIES = "GET_CITIES"
export const GET_CITIES_ERROR = "GET_CITIES_ERROR"

